# Generated by Django 5.1.1 on 2024-10-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luna', '0003_reserva_restaurante_alter_reserva_administrador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='Id_restaurante',
            new_name='id_restaurante',
        ),
    ]
